name: Create Repository

on:
  workflow_dispatch:

jobs:
  create_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Create Repository
      uses: actions/github-script@v4
      env:
        REPO_NAME: introduction-to-github
        REPO_DESCRIPTION: A repository for learning the basics of GitHub
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data } = await github.repos.createForAuthenticatedUser({
            name: process.env.REPO_NAME,
            description: process.env.REPO_DESCRIPTION,
            private: false
          });
          console.log(`Repository created: ${data.html_url}`);