name: Create Repository

on:
  workflow_dispatch:

jobs:
  create_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Create Repository
      uses: f1lander/create-repository-action@v1.0.2
      with:
        name: 'introduction-to-github'
        access-token: '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'