name: 'Create Repo'

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  create_repo:
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Repository Dispatch
      id: check_repo
      uses: peter-evans/repository-dispatch@v2.1.1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: 'CSE110SP23Lab5-introduction-to-github'
        event-type: create-repo

    - name: Create GitHub Repo
      if: steps.check_repo.outputs == 'failure'
      id: create_repo
      uses: howlowck/create-repo-action@v1.0
      with:
        repoName: 'CSE110SP23Lab5-introduction-to-github'
        repoDescription: 'introduction-to-github'
        repoVisibility: 'public'
        securityToken: ${{ secrets.ACCESS_TOKEN }}
      
    - name: Print Repository URL
      run: |
          echo "Repository URL: ${{ steps.create_repo.outputs.repoUrl }}"