name: Create Repository

on: [push]

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Create a New Repository
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -d '{"name":"introduction-to-github"}' \
        https://api.github.com/user/repos