name: Create Repository

on:
  workflow_dispatch:

jobs:
  create_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Create Repository
      uses: f1lander/create-repository-action@1.0.0    
      with:
        name: 'repository-name'
        org: 'org-name'
        private: false
        access-token: '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'