name: Create Repo

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Create Repository
      id: create_repo
      uses: f1lander/create-repository-action@v1.0.2
      with:
        name: 'introduction-to-github'
        access-token: ${{ secrets.GITHUB_TOKEN }}

      